#!/bin/bash
#script que ejecuta un dock en un scritorio o entorno de scritorio específico
# process es el scritorio, daemon, servicio relacionado con el entorno de escritorio
# dock es el  dock que será ejecutado en dicho entorno. NOTA: debe especificar la path completo del ejecutable del dock

getPid(){
	pid=`ps -o pid,command ax | grep $1 | awk '!/awk/ && !/grep/ {print $1}'`;
}

echo -e "Iniciando el dock: "

process="gnome-panel"
getPid $process

if [ "${pid}" == "" ]; then		
	echo -e "no se puede iniciar, gnome-panel no esta corriendo"
else
		
	dock="/usr/bin/avant-window-navigator"
	getPid $dock		
	
	if [ "${pid}" == "" ]; then

		/usr/bin/avant-window-navigator > /dev/null 2>&1 &
		getPid $dock
		echo -e "se inició el dock $dock , corriendo con PID: $pid [\e[32mOK\e[39m]"

	else
		echo -e "Ya existe una instancia de $dock corriendo con el PID: $pid [\e[31mERROR\e[39m]"
	fi
fi
